language: python
cache: pip

python:
  - "2.7"
  - "3.5"
  - "3.6"
env:
  - FLASK=0.12
  - FLASK=0.11.1
  - FLASK=0.10.1

install:
  - pip install -U pip setuptools
  - pip install -e .[test]
  - pip install flask==$FLASK

script:
  - make test
  - make doc
  - make lint

notifications:
  email:
    - sf@fermigier.com
